# Generated by Django 4.2.11 on 2024-09-12 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_price', models.CharField(blank=True, max_length=5, null=True)),
                ('Select_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Kids', 'Kids')], max_length=10, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='HomePage/media/')),
            ],
            options={
                'verbose_name_plural': 'Card Data',
            },
        ),
        migrations.CreateModel(
            name='Product_Color_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Color',
            },
        ),
        migrations.CreateModel(
            name='Product_Size_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Size',
            },
        ),
        migrations.CreateModel(
            name='Product_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], null=True)),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.card_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Rating',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.card_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='card_model',
            name='Product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.product_color_model'),
        ),
        migrations.AddField(
            model_name='card_model',
            name='Product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.product_size_model'),
        ),
    ]
