# Generated by Django 4.2.11 on 2024-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_selectfavorite_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectfavorite_cloth',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
