# Generated by Django 4.2.11 on 2024-09-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_remove_card_model_rating_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Rating',
        ),
    ]
